### ISSUE TITLE
Return Error if receive buffer is too small for message

### ISSUE THREAD

**Issue by mcsherrylabs** [input-output-hk/ce-netsim#15]
Currently we copy as much of the outgoing message as we can into the given buffer. 
This will return incomplete messages without error.

Probably better to return an error in the case the given buffer is too small.

netsim-ffi -> lib.rs -> netsim_socket_recv

**Comment by NicolasDP** [comment]
Good point, can you do it ?

**Comment by mcsherrylabs** [comment]
I'll assign to myself when I can do it...
